const Map<String, List<Map<String, String>>> kCompanionOptionPatches =
    <String, List<Map<String, String>>>{
  'v4.shoulderProp': <Map<String, String>>[
    {'value': 'sheetGhost', 'label': 'Sheet ghost'},
    {'value': 'miniSkeleton', 'label': 'Mini skeleton'},
    {'value': 'skullHands', 'label': 'Skull with hands'},
    {'value': 'miniReaper', 'label': 'Mini reaper'},
    {'value': 'zombieHead', 'label': 'Zombie head'},
    {'value': 'vampireBat', 'label': 'Vampire bat'},
    {'value': 'greyAlien', 'label': 'Grey alien'},
    {'value': 'alienBlob', 'label': 'Alien blob'},
    {'value': 'miniUfo', 'label': 'Mini UFO'},
    {'value': 'cosmicParasite', 'label': 'Cosmic parasite'},
    {'value': 'miniAstronaut', 'label': 'Mini astronaut'},
    {'value': 'cosmicJellyfish', 'label': 'Cosmic jellyfish'},
    {'value': 'arcadeChomper', 'label': 'Arcade chomper'},
    {'value': 'arcadeGhost', 'label': 'Arcade ghost'},
    {'value': 'joystickBuddy', 'label': 'Joystick buddy'},
    {'value': 'pixelHeartBuddy', 'label': 'Pixel heart buddy'},
    {'value': 'arcadeCabinet', 'label': 'Mini arcade cabinet'},
    {'value': 'diceBuddy', 'label': 'Dice buddy'},
    {'value': 'serviceBot', 'label': 'Service robot'},
    {'value': 'scoutDrone', 'label': 'Scout drone'},
    {'value': 'robotSpider', 'label': 'Robot spider'},
    {'value': 'hologramAssistant', 'label': 'Hologram assistant'},
    {'value': 'radioBuddy', 'label': 'Radio buddy'},
    {'value': 'miniGriffin', 'label': 'Mini griffin'},
    {'value': 'fairy', 'label': 'Fairy'},
    {'value': 'mandrake', 'label': 'Mandrake'},
    {'value': 'miniGolem', 'label': 'Mini golem'},
    {'value': 'miniMimic', 'label': 'Mini mimic'},
    {'value': 'fireSprite', 'label': 'Fire sprite'},
    {'value': 'floatingEye', 'label': 'Floating eye'},
    {'value': 'rat', 'label': 'Rat'},
    {'value': 'raccoon', 'label': 'Raccoon'},
    {'value': 'chameleon', 'label': 'Chameleon'},
    {'value': 'gecko', 'label': 'Gecko'},
    {'value': 'octopus', 'label': 'Mini octopus'},
    {'value': 'snail', 'label': 'Snail'},
    {'value': 'stormCloud', 'label': 'Storm cloud'},
    {'value': 'flameOrb', 'label': 'Flame orb'},
    {'value': 'blackHole', 'label': 'Mini black hole'},
    {'value': 'slime', 'label': 'Slime'},
    {'value': 'coffeeBuddy', 'label': 'Coffee buddy'},
    {'value': 'donutBuddy', 'label': 'Donut buddy'},
    {'value': 'emojiOrb', 'label': 'Emoji orb'},
    {'value': 'miniBlackCatCloud', 'label': 'Black cat cloud'},
  ],
  'v4.extraShoulderProp': <Map<String, String>>[
    {'value': 'sheetGhost', 'label': 'Sheet ghost'},
    {'value': 'miniSkeleton', 'label': 'Mini skeleton'},
    {'value': 'skullHands', 'label': 'Skull with hands'},
    {'value': 'miniReaper', 'label': 'Mini reaper'},
    {'value': 'zombieHead', 'label': 'Zombie head'},
    {'value': 'vampireBat', 'label': 'Vampire bat'},
    {'value': 'greyAlien', 'label': 'Grey alien'},
    {'value': 'alienBlob', 'label': 'Alien blob'},
    {'value': 'miniUfo', 'label': 'Mini UFO'},
    {'value': 'cosmicParasite', 'label': 'Cosmic parasite'},
    {'value': 'miniAstronaut', 'label': 'Mini astronaut'},
    {'value': 'cosmicJellyfish', 'label': 'Cosmic jellyfish'},
    {'value': 'arcadeChomper', 'label': 'Arcade chomper'},
    {'value': 'arcadeGhost', 'label': 'Arcade ghost'},
    {'value': 'joystickBuddy', 'label': 'Joystick buddy'},
    {'value': 'pixelHeartBuddy', 'label': 'Pixel heart buddy'},
    {'value': 'arcadeCabinet', 'label': 'Mini arcade cabinet'},
    {'value': 'diceBuddy', 'label': 'Dice buddy'},
    {'value': 'serviceBot', 'label': 'Service robot'},
    {'value': 'scoutDrone', 'label': 'Scout drone'},
    {'value': 'robotSpider', 'label': 'Robot spider'},
    {'value': 'hologramAssistant', 'label': 'Hologram assistant'},
    {'value': 'radioBuddy', 'label': 'Radio buddy'},
    {'value': 'miniGriffin', 'label': 'Mini griffin'},
    {'value': 'fairy', 'label': 'Fairy'},
    {'value': 'mandrake', 'label': 'Mandrake'},
    {'value': 'miniGolem', 'label': 'Mini golem'},
    {'value': 'miniMimic', 'label': 'Mini mimic'},
    {'value': 'fireSprite', 'label': 'Fire sprite'},
    {'value': 'floatingEye', 'label': 'Floating eye'},
    {'value': 'rat', 'label': 'Rat'},
    {'value': 'raccoon', 'label': 'Raccoon'},
    {'value': 'chameleon', 'label': 'Chameleon'},
    {'value': 'gecko', 'label': 'Gecko'},
    {'value': 'octopus', 'label': 'Mini octopus'},
    {'value': 'snail', 'label': 'Snail'},
    {'value': 'stormCloud', 'label': 'Storm cloud'},
    {'value': 'flameOrb', 'label': 'Flame orb'},
    {'value': 'blackHole', 'label': 'Mini black hole'},
    {'value': 'slime', 'label': 'Slime'},
    {'value': 'coffeeBuddy', 'label': 'Coffee buddy'},
    {'value': 'donutBuddy', 'label': 'Donut buddy'},
    {'value': 'emojiOrb', 'label': 'Emoji orb'},
    {'value': 'miniBlackCatCloud', 'label': 'Black cat cloud'},
  ],
};
